### PR TITLE
Update readme file

### PR DESCRIPTION
**Pull request by jldelda**
Hello! I am a big fan of this project.

My addition to the repo is the Readme file. I have been trying to replicate a Cityscope with no success, but at least I have acquired a decent schema of it that I would like to share with others.

Feel free to reject the pull if the schema is confusing. I would like to keep collaborating by doing a step by step process on *how to build your first Cityscope*.

### CODE REVIEW

**Comment by RELNO** [comment]
@jldelda thanks for sharing your PR. 
Without going into too much details, I think that your edits could be well integrated into one [or more] or the repos concerning an actual CityScope TUI. This repo is really a very high level intro to CS, and we want to keep it clear that there are many different ways by which CityScope can be deployed, not all involve scanning+model+projection. 

One more thing is that  Gama model is one part of the system. CityScope 'talks' to Rhino, Unity, JS, Py, Gama and virtually any tool that can parse a simple grid and perform computation/visualization.

**Comment by yasushisakai** [comment]
@jldelda thank you for your time on this. I think it is good and clear.

> I have been trying to replicate a Cityscope with no success

I think we can help and use this opportunity to make it easily deploy-able/

@RELNO 's point, I think it is actually better to make this look like a stream lined approach and gradually communicate that there are different methods to connect/deploy. First we want to have the simplest tool chain (IMO JS version) to run for a low entry point. Preferably without code.

**Comment by jldelda** [comment]
Thanks @RELNO  and @yasushisakai for the clarifications. Let me know if I can help documenting an easy deploy-able CS. I have also been in contact with @agrignard and Luis regarding this.

**Comment by RELNO** [comment]
@jldelda as a matter a fact we are working on an easy[er] version. I'd be very happy to get your input on it. It is very much WIP and docs are still not there, but any alpha testing is welcomed:
A 'sandbox' version is here: https://cityscope.github.io/CS_cityscopeJS/
Test the 'sandbox' table here: https://cityscope.github.io/CS_cityscopeJS/TEST/test.html
[the latter can also be projected to a table using: https://cityscope.github.io/CS_prjmapJS/]
The tool repo is here: https://github.com/CityScope/CS_cityscopeJS
CityIO Frontend is here [to see dataviz for your table]: https://cityscope.github.io/CS_CityIO_Frontend/

**Comment by jldelda** [comment]
Thank you very much @RELNO, you have just connected me the dots that I needed.

I will deploy it and will let you know how it went.

**Pull request closed without merging**
